### ISSUE TITLE
Allow selecting language other than English in retail?

### ISSUE THREAD

**Issue by orriduck** [rubenzantingh/MultiLanguage#1]
Hi, @rubenzantingh,

I've downloaded the multilanguage plugin from curseforge for my retail version WOW. When looking into the options, I seems can only select English in the list of options. This plugin is really helpful for me, appreciate all the work!
<img width="304" alt="image" src="https://github.com/rubenzantingh/MultiLanguage/assets/31749673/a1200cf1-f20b-425b-8568-fb5c97124256">

Is there a plan openning up more languages including Chinese? Or is there anything I should do to make it happen?

**Comment by rubenzantingh** [comment]
Hey Orriduck,

Sorry for the late reply, I'm glad you're enjoying the addon! I am currently in the process of releasing the other language packs. You can check the description on Curseforge or the readme here for the links. Chinese has already been released.

The reason these are not included in one package like for classic (era) is that the dataset for retail is quite large. I don't want to force everyone to download them all as this would take up a lot of disk space and maybe even slow down the game's initial loading time. 

As I don't have the time to play the game a lot, I really appreciate any bug reports as well if you encounter them.
