### ISSUE TITLE
Problem with setting a hotkey

### ISSUE THREAD

**Issue by Alyndel** [rubenzantingh/MultiLanguage#4]
Hello !

I have a French keyboard, and we have two ALT keys, the one on the left is classic, and the one on the right is called ALT GR.

When i try to set ALT GR as Hotkey, your add-on thinks i binded LCTRL.

Is there a way for you to fix it ?

Thanks in advance

**Comment by rubenzantingh** [comment]
Hey Alyndel,

Sorry to hear that you're running into this issue. I've read a bit into this and see a fair amount of cases where a program interprets the ALT GR key as CTRL + ALT, which then binds CTRL. Can you try binding an ability in the game to ALT GR to see if that does work as intended?

Kind regards,

Ruben

**Comment by Alyndel** [comment]
Hello again,

as intended, ALT GR in WoW is, as you said, binding CTRL + ALT.

However, i binded RCTRL, since i'm not using it.

Sorry to have bother you, great add-on by the way !

**Comment by rubenzantingh** [comment]
Hey Alyndel,

Not a bother at all, hope you enjoy using it! Glad you managed to find a workaround.

Kind regards,

Ruben
