### ISSUE TITLE
The image of the quest target overlaps the translation text

### ISSUE THREAD

**Issue by Shenn2948** [rubenzantingh/MultiLanguage#5]
![WoWScrnShot_110224_123314](https://github.com/user-attachments/assets/1c0fa99b-3c70-45d9-bc18-e01fd942a39e)

Some quests have an image of the target. It covers the translation text and you can't read it.
Game version: The War Within, 11.0.5

**Comment by Shenn2948** [comment]
It would be great if there was an option to display the translation text in the quest window itself and switch the translation with a button, this could also solve the problem mentioned above. (in the screenshots you can see how this is implemented in another addon WoWpoPolsku)
![WoWScrnShot_110224_124232](https://github.com/user-attachments/assets/66b694fe-aee9-47ea-bb20-8999aa09b866)
![WoWScrnShot_110224_124225](https://github.com/user-attachments/assets/beb6e00c-b90f-425f-8281-bfbe5fb9617e)

**Comment by rubenzantingh** [comment]
Hey Shenn2948,

First of all, thanks for your extremely detailed report. I will make sure the issue you reported will be resolved, hopefully somewhere this week is manageable. 

As for the feature request, I have added this to the top of the list of features that I have yet to implement. I think it's a terrific idea but will need time to investigate how to do it.

Kind regards,

Ruben

**Comment by rubenzantingh** [comment]
Hey Shenn2948,

I just released a new version which moves the translation frame to the right of the model when the model is displayed. Hopefully this works for you while I start development on the in-frame feature.

Kind regards,

Ruben Zantingh

**Comment by Shenn2948** [comment]
thank you very much for the great addon and quick fix, everything works fine now
